export interface CreateCycleTimeCOA {
    userId: string;
    startDate: Date;
    year: number;
    month: string;
    trip: number;
    fleet: string;
    tugboat_spob: string;
    ob_spob: string;
    route: string;
    estimatedFuel: number;
    actualFuel: number;
    arrivedInLoadingDock: Date;
    orderAssistTugboatEntry: Date;
    startAnchorUp: Date;
    finishAnchorUp: Date;
    assistConnectEntry: Date;
    docking: Date;
    loadingMasterOnboard: Date;
    startLoading: Date;
    finishLoading: Date;
    startSounding: Date;
    finishSounding: Date;
    orderAssistTugboatExit: Date;
    assistConnectExit: Date;
    castOff: Date;
    fullAway_STS: Date;
    arrivedAt_STS: Date;
    orderAssistTugboatEntry_STS: Date;
    assistConnectEntry_STS: Date;
    docking_STS: Date;
    loadingMasterOnboard_STS: Date;
    startLoading_STS: Date;
    finishLoading_STS: Date;
    startSounding_STS: Date;
    finishSounding_STS: Date;
    orderAssistTugboatExit_STS: Date;
    assistConnectExit_STS: Date;
    castOff_STS: Date;
    fullAway_discharge: Date;
    arrivedAt_discharge: Date;
    orderAssistTugboatEntry_discharge: Date;
    startAnchorUp_discharge: Date;
    finishAnchorUp_discharge: Date;
    assistConnectEntry_discharge: Date;
    docking_discharge: Date;
    loadingMasterOnboard_discharge: Date;
    startDischarge_discharge: Date;
    finishDischarge_discharge: Date;
    documentCargoOnboard_discharge: Date;
    orderAssistTugboatExit_discharge: Date;
    assistConnectExit_discharge: Date;
    castOff_discharge: Date;
    arrivedInPulauAtas: Date;
    fullAwayAfterDischarge: Date;
    arrivedInLoadingDock_2: Date;
}

export interface EditCycleTimeCOA {
    userId: string;
    startDate: string | null;
    year: number | null;
    month: string | null;
    trip: number | null;
    fleet: string | null;
    tugboat_spob: string | null;
    ob_spob: string | null;
    route: string | null;
    estimatedFuel: number | null;
    actualFuel: number | null;
    arrivedInLoadingDock: Date | null;
    orderAssistTugboatEntry: Date | null;
    startAnchorUp: Date | null;
    finishAnchorUp: Date | null;
    assistConnectEntry: Date | null;
    docking: Date | null;
    loadingMasterOnboard: Date | null;
    startLoading: Date | null;
    finishLoading: Date | null;
    startSounding: Date | null;
    finishSounding: Date | null;
    orderAssistTugboatExit: Date | null;
    assistConnectExit: Date | null;
    castOff: Date | null;
    fullAway_STS: Date | null;
    arrivedAt_STS: Date | null;
    orderAssistTugboatEntry_STS: Date | null;
    assistConnectEntry_STS: Date | null;
    docking_STS: Date | null;
    loadingMasterOnboard_STS: Date | null;
    startLoading_STS: Date | null;
    finishLoading_STS: Date | null;
    startSounding_STS: Date | null;
    finishSounding_STS: Date | null;
    orderAssistTugboatExit_STS: Date | null;
    assistConnectExit_STS: Date | null;
    castOff_STS: Date | null;
    fullAway_discharge: Date | null;
    arrivedAt_discharge: Date | null;
    orderAssistTugboatEntry_discharge: Date | null;
    startAnchorUp_discharge: Date | null;
    finishAnchorUp_discharge: Date | null;
    assistConnectEntry_discharge: Date | null;
    docking_discharge: Date | null;
    loadingMasterOnboard_discharge: Date | null;
    startLoading_discharge: Date | null;
    finishLoading_discharge: Date | null;
    documentCargoOnboard_discharge: Date | null;
    orderAssistTugboatExit_discharge: Date | null;
    assistConnectExit_discharge: Date | null;
    castOff_discharge: Date | null;
    arrivedInPulauAtas: Date | null;
    fullAwayAfterDischarge: Date | null;
    arrivedInLoadingDock_2: Date | null;
}